/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ssolver;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.stage.Popup;
import javafx.stage.Stage;
import ssolver.gui.MainPane;
import ssolver.solver.Solver;

import java.net.URL;

public class App extends Application {

    private static Stage primaryStage;
    private MainPane root;

    @Override
    public void start(Stage primaryStage) throws Exception {
        this.primaryStage = primaryStage;
        primaryStage.setTitle("ssolver");

        root = new MainPane();
        root.setSolveClickListener(this::solve);

        // Create the grid
        var scene = new Scene(root);

        URL styleRes = getClass().getResource("style.css");
        if (styleRes != null) {
            scene.getStylesheets().add(styleRes.toExternalForm());
        }
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private void solve(int[][] numbers) {
        Solver s = new Solver();
        var result = s.solve(numbers);

        if (result != null) {
            root.setBoard(result);
        } else {
            showErrorMsg("That doesn't seem to be a valid puzzle");
            root.reloadBoard();
        }
    }

    private void showErrorMsg(String msg) {
        Alert alert = new Alert(Alert.AlertType.ERROR, msg);
        alert.showAndWait();
    }

    public static Stage getPrimaryStage() {
        return primaryStage;
    }

    public static void main(String[] args) {
        launch(args);
    }
}
